version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "04:17"
      timezone: Asia/Singapore
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "04:47"
      timezone: Asia/Singapore
    open-pull-requests-limit: 5
